name: Wealthplex
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./my-app
      dockerfile : Dockerfile
    ports:
      - "3000:3000"